### PR TITLE
add api to login/register student and Add a file to write database instructions

### PR DESCRIPTION
**Pull request by Ammar22-star0**
The login process is done by generating token ,Before generating the token, the password is encrypted, and then the token is given to each user who registers on the site

### CODE REVIEW

**Review by YAMANX8 — APPROVED** [review]
great job ammar!

**Comment by 9ahmd0** [comment]
wow what a solution
keep going sir

**Review by 9ahmd0 — APPROVED** [review]
wow

**Review by ahmedahmedomer — APPROVED** [review]
nice

**Pull request merged**
